name: build
on: [push]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
   build_windows:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: build
        run: |
          ./gradlew publishRelease --track=production
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: 2.3.0-beta3
          path: /app/build/outputs/apk/
