name: build
on: [push]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
   build_windows:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
      - uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.8.20
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: build
        run: |
          ./gradlew assembleRelease
          # gradle clean
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: datmusic-2.3.0-beta3
          path: ./app/build/outputs/apk/
